version: "3"
services:
  postgres:
    image: postgres:10.1
    ports:
      - "5432:5432"
  app:
    build: .
    image: atayarani/game-menu:0.0.6
    depends_on:
      - postgres
    volumes:
      - .:/home/app/webapp
    ports:
      - "8080:80"
    environment:
      - RAILS_ENV=development
      - DB_NAME=game-menu_development
      - DB_HOST=postgres
      - BGG_USERNAME=atayarani
